### ISSUE TITLE
Not working on RouterOS v6.44

### ISSUE THREAD

**Issue by qferiz** [massimo-filippi/mikrotik#9]
I'm follow step by step, and copy source code on Script, but not working on RouterOS v6.44.

My routerBoard RB850Gx2 RouterOS v6.44.

I try run this script, and show LOG at Winbox.

It should be notice LOG :

> `:log info ("No firmware nor RouterOS upgrade found.")`

but, nothing happen... :(

Because, RouterOS v6.44 is latest version.

Please help mee....

Thanks :)

**Comment by TheUserDead** [comment]
You need wait some %future% time for newer version of RouterOS.
You can try call Dr. Brown and ask take you to ~1 month ahead, and test your script :)

For serious i have modified script for easy level users without any external notification. Only logs. 
I just add :log info "Checking updates..." before first command /system package update
And replace old channel (current > stable) and all working fine.
You can check my light script with yours
[helping.txt](https://github.com/massimo-filippi/mikrotik/files/2936305/helping.txt)
And don't forgot to wait (cause script have some delays) and check Jobs tab in winbox when you want restart script

**Comment by maximkrusina** [comment]
Seems to be solved. Otherwise let me know! Thanx!
